### ISSUE TITLE
isn't it easier to program a memory directly with a clip?

### ISSUE THREAD

**Issue by nonflammable** [c-/AiLight-Flasher#1]
![Programmer-Testing-Clip-SOP8-SOP-SOIC-8-SOIC8-DIP8-DIP-8-Pin-IC-Test-Clamp](https://user-images.githubusercontent.com/6041490/63217007-d65c0a00-c13e-11e9-8fff-d28246355c72.jpg)

**Comment by c-** [comment]
Yes.

Good luck getting a clip to work with the form factor of these devices.

**Comment by nonflammable** [comment]
I don't have an AiLight bulb. Just asking.
If connecting the clip is not possible, it is clear that you have done a great job.

**Comment by c-** [comment]
Yeah, definitely no way to use any kind of off-the-shelf clip I've ever seen. The test points the clip would need to hit are in a strange pattern, and the clip would have to have an opening about the length of a regular light bulb...

**Comment by nonflammable** [comment]
I still don't understand the problem with the clip being attached
![IMG_20190821_145327700_HDRm](https://user-images.githubusercontent.com/6041490/63434351-34ca0680-c425-11e9-807e-a88478bbf7ea.jpg)
![IMG_20190821_145257945_HDRm](https://user-images.githubusercontent.com/6041490/63434374-3d224180-c425-11e9-8198-a4e7c57b80b2.jpg)
![Ai_Light_wired](https://user-images.githubusercontent.com/6041490/63434394-47dcd680-c425-11e9-8a36-8981afd912ca.jpg)

**Comment by c-** [comment]
Ah, you mean a clip to program the flash chip directly. Sure, that would probably work. I don't have one, but I do have a PCB mill, pogo pins, and pin headers.
